
name: Docker CI

# Trigger the workflow on pushes to the master branch
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    # Use the latest Ubuntu environment to run the job
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Use GitHub secrets for secure credentials
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx for multi-architecture builds (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Use the current directory as the build context
          context: .
          # Use your Dockerfile
          file: ./Dockerfile
          # Push the image to Docker Hub
          push: true
          # Define the image tags (latest and a version tag if desired)
          tags: |
            mikdar/cyber-llm:latest
          # Enable caching for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
